version: "3.8"
services:
    keycloak-server_2:
        container_name: keycloak-server_2
# use keycloak 20.0
        image: quay.io/keycloak/keycloak
        environment:
            # create initial username and password
#            KEYCLOAK_USER: admin
#            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            PROXY_ADDRESS_FORWARDING: "true"
            KEYCLOAK_FRONTEND_URL: http://localhost:10001/auth
#            KEYCLOAK_IMPORT: /tmp/realm-export.json#        volumes:
#            - ./realm-export.json:/tmp/realm-export.json
# new import commands einbauen!
        command:
        - start-dev 
        - --import-realm
        volumes:
            - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
#            - ./realm-export.json:/tmp/realm-export.json
        ports:
            - 10001:8080
#        networks:
#            - tea-network

    mongo_db_2:
        image: "mongo"
        container_name: mongo_db_2
        restart: always
        ports:
            - 27017:27017
#        networks:
#            - tea-network
            
    teas_rs:
        build: ./teas
        image: teapot2_teas_rs
        container_name: teas_rs
        environment:
            - MONGODB_HOST=mongo_db_2
            - DATABASE_NAME=teas2-db
#        restart: always
        ports:
            - 8184:8184
        depends_on:
            - mongo_db_2
#        networks:
#            - tea-network
            
#    milk:
#        build: ./milk
#        container_name: milk
#        image: teapot2_milk
#        ports:
#            - 8183:8183
#        networks:
#            - tea-network
            
    gateway_rs:
        build: ./gateway2
        image: teapot2_gateway_rs
        container_name: gateway_rs
        environment:
            - TEAS=http://host.docker.internal:8184
            - MILK=http://host.docker.internal:8183
#            - CLIENT_SECRET=49re8jq7d3WeYRx7BVHwoPSJFRxyhcKp
        # tried: host.docker.internal, keycloak-server, localhost
            - KEYCLOAK=http://host.docker.internal:10001 # see also #https://github.com/akramEsprit/spring-microservices/blob/master/docker-compose.yml
#        depends_on:
#            - discovery-service_10-3-23
            - keycloak-server_2
        ports:
            - 8180:8180
#        networks:
#            - tea-network
#        restart: always

#networks:
#  tea-network:
#    driver: bridge