version: "3.8"
services:
    keycloak-server_2:
        container_name: keycloak-server_2
        image: quay.io/keycloak/keycloak:20.0
        environment:
            # create initial username and password
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            PROXY_ADDRESS_FORWARDING: "true"
        command:
        - start-dev 
        - --import-realm
        volumes:
            - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
        ports:
            - 10001:8080
        networks:
            - tea-network

    mongo_db_2:
        image: "mongo"
        container_name: mongo_db_2
        restart: always
        ports:
            - 27017:27017
        networks:
            - tea-network
            
    teas_rs:
        build: ./teas
        image: teapot2_teas_rs
        container_name: teas_rs
        environment:
            - MONGODB_HOST=mongo_db_2
            - DATABASE_NAME=teas2-db
            - KEYCLOAK=http://host.docker.internal:10001
#        restart: always
        ports:
            - 8184:8184
        depends_on:
            - mongo_db_2
        networks:
            - tea-network
            
    gateway2_client:
        build: ./gateway2
        image: teapot2_gateway_client
        container_name: gateway_client
        environment:
            - TEAS=http://host.docker.internal:8184
            - MILK=http://host.docker.internal:8183
            - CLIENT_SECRET=4UBWQgAvTOWUh6ZnLC9dRR75WEFuidz4
            - KEYCLOAK=http://host.docker.internal:10001 # see also #https://github.com/akramEsprit/spring-microservices/blob/master/docker-compose.yml
            - keycloak-server_2
        ports:
            - 8181:8181
        networks:
            - tea-network
#        restart: always

networks:
  tea-network:
    driver: bridge