#! no special characters here, not even in comments, otherwise build error because of encoding!
server:
  port: 8184

spring:
  application:
    name: teaservice

  data:
    mongodb:
      port: 27017
  # nur docker
      host: ${MONGODB_HOST}
  #name, unter dem die datenbank angelegt, bzw. gefunden werden kann
      database: ${DATABASE_NAME}}

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${KEYCLOAK}/realms/teapot
          jwk-set-uri: ${KEYCLOAK}/realms/teapot/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:10001/auth/realms/teapot
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:10001/auth/realms/teapot/protocol/openid-connect/certs
#deprecated?
#spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:10001/auth/realms/teapot/protocol/openid-connect/token


  # discovery-service is the name of the container. change to localhost, when running without container
  #eureka.client.serviceUrl.defaultZone = http://discovery-service:8761/eureka