version: "3.8"
services:
  teaservice:
#    image: "teas-mongodocker"
    build: .
    restart: always
    ports:
      - 8084:8084
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo"
    restart: always
    ports:
      - 27017:27017
