server:
  port: 8181

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway2
  cloud:
    gateway:
      routes:
        - id: helloTea
          uri: ${TEAS}
          predicates:
            - Path=/hellotea/{name}
          filters:
            - SetPath=/teas/hello/{name}

        - id: listTeas
          uri: ${TEAS}
          predicates:
            - Path=/listteas
          filters:
            - SetPath=/teas/getall

        - id: makeTea
          uri: ${TEAS}
          predicates:
            - Path=/maketea/{teaID}
          filters:
            - SetPath=/teas/maketea/{teaID}

#        - id: milk
#          uri: ${MILK}
#          predicates:
#            - Path=/milk
#          filters:
#            - SetPath=/getmilk

      default-filters:
        - TokenRelay=

  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            jwk-set-uri: ${KEYCLOAK.SERVER-URL}/realms/teapot/protocol/openid-connect/certs
            issuer-uri: ${KEYCLOAK.SERVER-URL}/realms/teapot
        registration:
          keycloak-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: teapot-gateway
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:8181/login/oauth2/code/{registrationId}'