server:
  port: 8080

spring:
  application:
    name: gateway2
  cloud:
    gateway:
      routes:
        - id: helloTea
          uri: ${TEAS}
          predicates:
            - Path=/hellotea/{name}
          filters:
            - SetPath=/teas/hello/{name}

        - id: listTeas
          uri: ${TEAS}
          predicates:
            - Path=/listteas
          filters:
            - SetPath=/teas/getall

        - id: makeTea
          uri: ${TEAS}
          predicates:
            - Path=/maketea/{teaID}
          filters:
            - SetPath=/teas/maketea/{teaID}

        - id: milk
          uri: ${MILK}
          predicates:
            - Path=/milk
          filters:
            - SetPath=/getmilk